apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monsterstack-elie
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/e-lie/monsterstack-argocd-tp
    targetRevision: master ## ou autre branche
    path: manifests/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monsterstack-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true